# Generated by Django 5.2.3 on 2025-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_site_alter_devicemetric_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricssubcription",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
